import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

import { hash } from '../lib/contracts.mjs';
import {
  canonicalizeProtectedHeaders, classifyHealthcheckRuntime, fetchImmutableConfigBlob, parseAnonymousBearerChallenge, parseApprovedSourceReference, projectConfigBlobRedirect, resolveRegistryDigest,
  parseRegistryTokenResponse, platformCompatible, projectIndexPlatformDescriptors, projectProtectedResponseHeaders,
  selectCompatiblePlatform, validateRegistryResolverContract, validateResponseCookieNonParticipation,
} from '../lib/registry-digest-resolver.mjs';

const load = () => JSON.parse(fs.readFileSync(new URL('../contracts/registry-digest-resolver-contract.json', import.meta.url), 'utf8'));
const clone = structuredClone;
const H = character => character.repeat(64);
const digest = bytes => `sha256:${hash(bytes)}`;
const json = value => Buffer.from(JSON.stringify(value), 'utf8');
const code = expected => error => error?.code === expected;
const platform = { os: 'linux', architecture: 'arm64', variant: 'v8' };
const source = () => load().approved_sources.find(row => row.role === 'AUTH');
const raw = (...pairs) => pairs.flat();
const challenge = ({ realm='https://auth.docker.io/token', service='registry.docker.io', scope='repository:supabase/gotrue:pull', separator=',' }={}) => `Bearer realm="${realm}"${separator}service="${service}"${separator}scope="${scope}"`;
const tokenPath = '/token?service=registry.docker.io&scope=repository%3Asupabase%2Fgotrue%3Apull';
const cookieContext = (responseCookie, overrides={}) => ({ contract:load(), host:'auth.docker.io', path:tokenPath, purpose:'ANONYMOUS_TOKEN', requestHeaders:{accept:'application/json'}, cookieJar:'FORBIDDEN', responseStatusCode:200, responseCookie, ...overrides });
const select = index => selectCompatiblePlatform(index, load());

function response(bytes, type, digestValue = digest(bytes), status = 200, extra = {}) {
  return { status, headers: { 'content-type': type, 'docker-content-digest': digestValue, ...extra }, body: bytes };
}

function artifacts({ indexType = 'application/vnd.oci.image.index.v1+json', manifestType = 'application/vnd.oci.image.manifest.v1+json', descriptors = null, configValue = null } = {}) {
  const contract = load();
  const config = configValue ?? { architecture: 'arm64', os: 'linux', config: { User: '1000', WorkingDir: '/work', Entrypoint: ['/entrypoint'], Cmd: ['serve'], Volumes: { '/data': {} }, ExposedPorts: { '9999/tcp': {} }, Healthcheck: { Test: ['CMD','check'], Interval: 1000000, Timeout: 1000000, Retries: 1, StartPeriod: 0 } } };
  const configBytes = json(config), configDigest = digest(configBytes);
  const child = { schemaVersion: 2, mediaType: manifestType, config: { mediaType: contract.media_types.configs[0], size: configBytes.length, digest: configDigest }, layers: [{ mediaType: 'application/vnd.oci.image.layer.v1.tar+gzip', size: 1, digest: `sha256:${H('9')}` }] };
  const childBytes = json(child), childDigest = digest(childBytes);
  const manifestRows = descriptors ?? [{ mediaType: manifestType, size: childBytes.length, digest: childDigest, platform: clone(platform) }];
  const index = { schemaVersion: 2, mediaType: indexType, manifests: manifestRows };
  const indexBytes = json(index);
  return { contract, config, configBytes, configDigest, child, childBytes, childDigest, index, indexBytes,
    indexResponse: response(indexBytes,indexType), childResponse: response(childBytes,manifestType), configResponse: { status:200,headers:{'content-type':'application/octet-stream'},body:configBytes } };
}

function anonymousQueue(a = artifacts()) {
  const challenge = `Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:supabase/gotrue:pull"`;
  return [
    { status:401,headers:{'www-authenticate':challenge},body:Buffer.from('unauthorized') },
    { status:200,headers:{'content-type':'application/json'},body:json({token:'safe.synthetic.token'}) },
    a.indexResponse, a.childResponse, a.configResponse,
  ];
}

const redirectLocation = 'https://cdn.example.test/registry/blobs/config?X-Signature=secret-value&X-Expires=60';
function redirectedQueue(a = artifacts(), location = redirectLocation, status = 307) {
  const queue = anonymousQueue(a);
  queue[4] = { status, headers: { location }, body: Buffer.alloc(0) };
  queue.push(a.configResponse);
  return queue;
}

function redirectProjection(overrides = {}) {
  const contract = load(), approvedSource = source(), requestedDigest = `sha256:${H('a')}`;
  return projectConfigBlobRedirect({ contract, source: approvedSource, requestedDigest,
    sourcePath: `/v2/${approvedSource.repository}/blobs/${requestedDigest}`,
    response: { status: 307, headers: { location: redirectLocation }, body: Buffer.alloc(0) }, ...overrides });
}

function replaceConfigBytes(a, bytes) {
  a.configBytes = bytes; a.configDigest = digest(bytes);
  a.child.config.size = bytes.length; a.child.config.digest = a.configDigest;
  a.childBytes = json(a.child); a.childDigest = digest(a.childBytes);
  a.index.manifests[0].size = a.childBytes.length; a.index.manifests[0].digest = a.childDigest;
  a.indexBytes = json(a.index);
  a.indexResponse = response(a.indexBytes, a.index.mediaType);
  a.childResponse = response(a.childBytes, a.child.mediaType);
  a.configResponse = { status: 200, headers: { 'content-type': 'application/octet-stream' }, body: bytes };
  return a;
}

async function fetchConfigWith(a, responses, overrides = {}) {
  const calls = [], queue = [...responses];
  const request = async spec => { calls.push(clone(spec)); assert.ok(queue.length > 0); return queue.shift(); };
  const result = await fetchImmutableConfigBlob({ contract: load(), source: source(), configDescriptor: a.child.config,
    layerDigests: a.child.layers.map(layer => layer.digest), requestedDigest: a.child.config.digest,
    authorization: 'Bearer safe.synthetic.token', request, ...overrides });
  return { result, calls };
}

async function resolveWith(queue, contract = load()) {
  const calls = [];
  const request = async spec => { calls.push(clone(spec)); assert.ok(queue.length > 0); return queue.shift(); };
  const result = await resolveRegistryDigest({ contract, role:'AUTH', sourceReference:'supabase/gotrue:v2.195.0', request, resolverSha256:H('a'), clock:()=>new Date('2000-01-01T00:00:00.000Z') });
  return { result, calls };
}

async function resolveHealthcheck(healthcheck) {
  const config = { architecture: 'arm64', os: 'linux', config: {} };
  if (healthcheck !== undefined) config.config.Healthcheck = healthcheck;
  const a = artifacts({ configValue: config });
  return resolveWith(anonymousQueue(a));
}

test('resolver contract is strict and fixed to public Docker Hub metadata', () => assert.equal(validateRegistryResolverContract(load()).resolver_id,'WINWIN_PUBLIC_REGISTRY_METADATA_V1'));
test('no Healthcheck projects as absent and non-executing', async () => { const {result}=await resolveHealthcheck(undefined); assert.equal(result.healthcheck.state,'ABSENT'); assert.equal(result.healthcheck.executable,false); });
test('Healthcheck NONE projects as disabled while retaining bounded timing evidence', async () => { const {result}=await resolveHealthcheck({Test:['NONE'],Interval:1000000}); assert.equal(result.healthcheck.state,'DISABLED'); assert.equal(result.healthcheck.test_form,'NONE'); assert.deepEqual(result.healthcheck.interval,{present:true,value_nanoseconds:1000000}); });
test('Healthcheck CMD records only bounded argv structure and payload hash', async () => { const {result}=await resolveHealthcheck({Test:['CMD','/bin/check','--ready']}); assert.equal(result.healthcheck.test_form,'CMD'); assert.equal(result.healthcheck.argv_element_count,2); assert.equal(result.healthcheck.payload_byte_length,24); assert.doesNotMatch(JSON.stringify(result),/\/bin\/check|--ready/); });
test('Healthcheck CMD-SHELL records only bounded shell payload structure and hash', async () => { const {result}=await resolveHealthcheck({Test:['CMD-SHELL','check || exit 1']}); assert.equal(result.healthcheck.test_form,'CMD-SHELL'); assert.equal(result.healthcheck.argv_element_count,null); assert.doesNotMatch(JSON.stringify(result),/check \|\| exit 1/); });
test('malformed Healthcheck Test is rejected', async () => await assert.rejects(()=>resolveHealthcheck({Test:'CMD'}),code('REGISTRY_CONFIG_HEALTHCHECK_TEST')));
test('empty Healthcheck Test is rejected', async () => await assert.rejects(()=>resolveHealthcheck({Test:[]}),code('REGISTRY_CONFIG_HEALTHCHECK_TEST')));
test('unknown Healthcheck Test form is rejected', async () => await assert.rejects(()=>resolveHealthcheck({Test:['OTHER','check']}),code('REGISTRY_CONFIG_HEALTHCHECK_TEST_FORM')));
test('unknown Healthcheck key is rejected', async () => await assert.rejects(()=>resolveHealthcheck({Test:['CMD','check'],Unknown:1}),code('REGISTRY_CONFIG_HEALTHCHECK')));
test('Healthcheck timing fields retain independent presence and nanosecond values', async () => { const {result}=await resolveHealthcheck({Test:['CMD','check'],Interval:1000000,Timeout:2000000,StartPeriod:0,StartInterval:3000000}); const h=result.healthcheck; assert.deepEqual([h.interval,h.timeout,h.start_period,h.start_interval],[{present:true,value_nanoseconds:1000000},{present:true,value_nanoseconds:2000000},{present:true,value_nanoseconds:0},{present:true,value_nanoseconds:3000000}]); });
test('Healthcheck Retries retains independent presence and value', async () => { const {result}=await resolveHealthcheck({Test:['CMD','check'],Retries:4}); assert.deepEqual(result.healthcheck.retries,{present:true,value:4}); });
for (const timing of [-1,1,1.5]) test(`invalid Healthcheck timing ${timing} is rejected`, async () => await assert.rejects(()=>resolveHealthcheck({Test:['CMD','check'],Interval:timing}),code('REGISTRY_CONFIG_HEALTHCHECK_VALUE')));
for (const retries of [-1,1.5]) test(`invalid Healthcheck retries ${retries} is rejected`, async () => await assert.rejects(()=>resolveHealthcheck({Test:['CMD','check'],Retries:retries}),code('REGISTRY_CONFIG_HEALTHCHECK_RETRIES')));
test('changed Healthcheck command changes its projection and selected Config hashes', async () => { const a=(await resolveHealthcheck({Test:['CMD','one']})).result,b=(await resolveHealthcheck({Test:['CMD','two']})).result; assert.notEqual(a.healthcheck.payload_sha256,b.healthcheck.payload_sha256); assert.notEqual(a.selected_config_sha256,b.selected_config_sha256); });
test('changed Healthcheck timing changes its projection and selected Config hashes', async () => { const a=(await resolveHealthcheck({Test:['CMD','check'],Interval:1000000})).result,b=(await resolveHealthcheck({Test:['CMD','check'],Interval:2000000})).result; assert.notEqual(a.healthcheck.projection_sha256,b.healthcheck.projection_sha256); assert.notEqual(a.selected_config_sha256,b.selected_config_sha256); });
test('explicit runtime executable Healthcheck overrides executable image Healthcheck', () => { const c=load(); const out=classifyHealthcheckRuntime({imageHealthcheck:{Test:['CMD','image-check']},runtimeHealthcheck:{Test:['CMD','runtime-check']},policy:c.healthcheck_policy}); assert.equal(out.classification,'B_EXECUTABLE_BUT_OVERRIDDEN_OR_DISABLED'); assert.equal(out.runtime_effect,'OVERRIDDEN'); });
test('explicit runtime NONE disables executable image Healthcheck while retaining inherited timing evidence', () => { const c=load(); const out=classifyHealthcheckRuntime({imageHealthcheck:{Test:['CMD','image-check'],Interval:15000000000},runtimeHealthcheck:{Test:['NONE']},policy:c.healthcheck_policy}); assert.equal(out.classification,'B_EXECUTABLE_BUT_OVERRIDDEN_OR_DISABLED'); assert.equal(out.runtime_effect,'DISABLED'); assert.equal(out.field_sources.Interval,'IMAGE'); assert.deepEqual(out.effective.interval,{present:true,value_nanoseconds:15000000000}); });
test('omitted runtime Healthcheck inherits executable image Healthcheck', () => { const c=load(); const out=classifyHealthcheckRuntime({imageHealthcheck:{Test:['CMD','image-check']},policy:c.healthcheck_policy}); assert.equal(out.classification,'C_EXECUTABLE_AND_INHERITED'); assert.equal(out.runtime_effect,'INHERITED'); });
test('runtime command override still inherits omitted image StartInterval under Moby field merge', () => { const c=load(); const out=classifyHealthcheckRuntime({imageHealthcheck:{Test:['CMD','image-check'],Interval:15000000000,StartInterval:1000000000},runtimeHealthcheck:{Test:['CMD-SHELL','runtime-check'],Interval:10000000000,StartInterval:0},policy:c.healthcheck_policy}); assert.equal(out.classification,'B_EXECUTABLE_BUT_OVERRIDDEN_OR_DISABLED'); assert.equal(out.field_sources.Test,'RUNTIME'); assert.equal(out.field_sources.StartInterval,'IMAGE'); assert.deepEqual(out.effective.start_interval,{present:true,value_nanoseconds:1000000000}); });
test('Healthcheck payload cannot trigger network activity during metadata resolution', async () => { const {calls}=await resolveHealthcheck({Test:['CMD-SHELL','curl https://unapproved.example/']}); assert.equal(calls.length,5); assert.equal(calls.some(call=>call.host==='unapproved.example'),false); });
test('source reference parsing is byte exact', () => assert.deepEqual(parseApprovedSourceReference(load(),'AUTH','supabase/gotrue:v2.195.0'),source()));
test('OCI index resolves exact linux arm64 v8 child and config descriptor', async () => { const a=artifacts(), {result}=await resolveWith(anonymousQueue(a)); assert.equal(result.top_level_manifest_digest,digest(a.indexBytes)); assert.equal(result.platform_child_digest,a.childDigest); assert.equal(result.config_digest,a.configDigest); assert.deepEqual(result.platform,platform); });
test('Docker manifest list media type is supported', async () => { const a=artifacts({indexType:'application/vnd.docker.distribution.manifest.list.v2+json',manifestType:'application/vnd.docker.distribution.manifest.v2+json'}); assert.equal((await resolveWith(anonymousQueue(a))).result.manifest_media_type,a.index.mediaType); });
test('single manifest is supported when config proves exact platform', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',variant:'v8',config:{}}}); const queue=anonymousQueue(a); queue.splice(2,2,response(a.childBytes,a.child.mediaType)); const {result}=await resolveWith(queue); assert.equal(result.top_level_manifest_digest,result.platform_child_digest); });
test('requested linux arm64 v8 accepts one explicit v8 descriptor', () => { const a=artifacts(); assert.equal(select(a.index).digest,a.childDigest); });
test('requested linux arm64 v8 accepts one descriptor with omitted variant', () => { const a=artifacts(); delete a.index.manifests[0].platform.variant; assert.equal(select(a.index).digest,a.childDigest); });
test('descriptor null variant is not widened into OCI index omission', () => { const a=artifacts(); a.index.manifests[0].platform.variant=null; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('requested linux arm64 v8 rejects incompatible explicit descriptor variant', () => { const a=artifacts(); a.index.manifests[0].platform.variant='v9'; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('linux arm v7 never satisfies requested arm v8', () => assert.equal(platformCompatible({os:'linux',architecture:'arm',variant:'v7'},{os:'linux',architecture:'arm',variant:'v8'}),false));
test('amd64 does not satisfy requested arm64', () => { const a=artifacts(); a.index.manifests[0].platform.architecture='amd64'; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('wrong OS is rejected', () => { const a=artifacts(); a.index.manifests[0].platform.os='windows'; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('zero compatible executable descriptors fails closed', () => { const a=artifacts(); a.index.manifests=[]; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('exactly one compatible descriptor is selected', () => { const a=artifacts(); a.index.manifests.unshift({...clone(a.index.manifests[0]),digest:`sha256:${H('8')}`,platform:{os:'linux',architecture:'amd64'}}); assert.equal(select(a.index).digest,a.childDigest); });
test('multiple compatible descriptors are ambiguous', () => { const a=artifacts(); a.index.manifests.push(clone(a.index.manifests[0])); assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_AMBIGUOUS')); });
test('explicit v8 plus omitted arm64 candidate coexistence is ambiguous', () => { const a=artifacts(); const omitted=clone(a.index.manifests[0]); delete omitted.platform.variant; omitted.digest=`sha256:${H('7')}`; a.index.manifests.push(omitted); assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_AMBIGUOUS')); });
test('unknown attestation descriptor is ignored as non-executable', () => { const a=artifacts(); a.index.manifests.unshift({mediaType:a.child.mediaType,size:1,digest:`sha256:${H('6')}`,platform:{os:'unknown',architecture:'unknown'},annotations:{'vnd.docker.reference.type':'attestation-manifest','vnd.docker.reference.digest':a.childDigest}}); const projection=projectIndexPlatformDescriptors(a.index,load()); assert.equal(projection[0].executable_candidate,false); assert.equal(projection[0].classification,'NON_RUNTIME_ATTESTATION'); assert.equal(select(a.index).digest,a.childDigest); });
test('descriptor missing architecture is ignored as non-executable', () => { const a=artifacts(); delete a.index.manifests[0].platform.architecture; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('descriptor missing OS is ignored as non-executable', () => { const a=artifacts(); delete a.index.manifests[0].platform.os; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('config architecture mismatch is rejected', async () => { const a=artifacts({configValue:{architecture:'amd64',os:'linux',config:{}}}); await assert.rejects(()=>resolveWith(anonymousQueue(a)),code('REGISTRY_CONFIG_PLATFORM')); });
test('config OS mismatch is rejected', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'windows',config:{}}}); await assert.rejects(()=>resolveWith(anonymousQueue(a)),code('REGISTRY_CONFIG_PLATFORM')); });
test('config explicit variant mismatch is rejected', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',variant:'v9',config:{}}}); await assert.rejects(()=>resolveWith(anonymousQueue(a)),code('REGISTRY_CONFIG_VARIANT')); });
test('config omitted variant is accepted only by the narrow arm64 v8 rule', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',config:{}}}); assert.deepEqual((await resolveWith(anonymousQueue(a))).result.platform,platform); });
test('config null variant is accepted as OCI-equivalent to omission', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',variant:null,config:{}}}); assert.deepEqual((await resolveWith(anonymousQueue(a))).result.platform,platform); });
test('direct single-platform manifest accepts config with omitted arm64 v8 variant', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',config:{}}}); const queue=anonymousQueue(a); queue.splice(2,2,response(a.childBytes,a.child.mediaType)); const {result}=await resolveWith(queue); assert.equal(result.top_level_manifest_digest,result.platform_child_digest); });
test('selector never chooses the first of ambiguous compatible descriptors', () => { const a=artifacts(); const omitted=clone(a.index.manifests[0]); delete omitted.platform.variant; omitted.digest=`sha256:${H('5')}`; a.index.manifests.unshift(omitted); assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_AMBIGUOUS')); });
test('selection is deterministic across nonmatching descriptor order', () => { const a=artifacts(); const nonmatching=[{...clone(a.index.manifests[0]),digest:`sha256:${H('3')}`,platform:{os:'linux',architecture:'amd64'}},{...clone(a.index.manifests[0]),digest:`sha256:${H('4')}`,platform:{os:'windows',architecture:'arm64',variant:'v8'}}]; const first={...a.index,manifests:[nonmatching[0],a.index.manifests[0],nonmatching[1]]}; const second={...a.index,manifests:[nonmatching[1],nonmatching[0],a.index.manifests[0]]}; assert.equal(select(first).digest,select(second).digest); });
test('omitted arm64 candidate plus conflicting explicit ARM64 variant is ambiguous', () => { const a=artifacts(); delete a.index.manifests[0].platform.variant; a.index.manifests.push({...clone(a.index.manifests[0]),digest:`sha256:${H('2')}`,platform:{os:'linux',architecture:'arm64',variant:'v9'}}); assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_AMBIGUOUS')); });
test('descriptor with no platform is ignored', () => { const a=artifacts(); delete a.index.manifests[0].platform; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_MISSING')); });
test('resolver schema freezes every platform selection policy value', () => { const contract=load(); const schema=JSON.parse(fs.readFileSync(new URL('../schemas/registry-digest-resolver.schema.json',import.meta.url),'utf8')); for(const [key,value] of Object.entries(contract.platform_selection_policy)) assert.equal(schema.$defs.platformSelection.properties[key].const,value,key); });
test('malformed manifest JSON fails closed', async () => { const bytes=Buffer.from('{'); const queue=anonymousQueue(); queue[2]=response(bytes,'application/vnd.oci.image.index.v1+json'); await assert.rejects(()=>resolveWith(queue),code('REGISTRY_MANIFEST_JSON')); });
test('missing Docker-Content-Digest fails closed', async () => { const queue=anonymousQueue(); delete queue[2].headers['docker-content-digest']; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_DIGEST_HEADER')); });
test('manifest digest mismatch fails closed', async () => { const queue=anonymousQueue(); queue[2].headers['docker-content-digest']=`sha256:${H('1')}`; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_DIGEST_MISMATCH')); });
test('unsupported manifest media type fails closed', async () => { const bytes=json({schemaVersion:2,mediaType:'application/example'}); const queue=anonymousQueue(); queue[2]=response(bytes,'application/example'); await assert.rejects(()=>resolveWith(queue),code('REGISTRY_UNSUPPORTED_MEDIA_TYPE')); });
test('unexpected redirect is rejected and never followed', async () => { const queue=anonymousQueue(); queue[0]={status:302,headers:{location:'https://foreign.example/'},body:Buffer.alloc(0)}; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_UNEXPECTED_REDIRECT')); });
test('credential-bearing or non-Bearer auth challenge is rejected', () => assert.throws(()=>parseAnonymousBearerChallenge('Basic realm="x"',source()),code('REGISTRY_AUTH_CHALLENGE')));
test('anonymous bearer challenge must use exact realm service and scope', () => assert.throws(()=>parseAnonymousBearerChallenge('Bearer realm="https://evil.example/token",service="registry.docker.io",scope="repository:supabase/gotrue:pull"',source()),code('REGISTRY_AUTH_REALM')));
test('one valid singleton protected header is preserved exactly', () => assert.deepEqual(canonicalizeProtectedHeaders(raw(['Content-Type','application/json']),load()),{'content-type':'application/json'}));
test('two byte-identical Docker digest lines collapse to one', () => { const value=`sha256:${H('1')}`; assert.equal(canonicalizeProtectedHeaders(raw(['Docker-Content-Digest',value],['docker-content-digest',value]),load())['docker-content-digest'],value); });
test('Docker digest duplicate differing by one byte fails', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['docker-content-digest',`sha256:${H('1')}`],['docker-content-digest',`sha256:${H('2')}`]),load()),code('REGISTRY_HEADER_CONFLICT')));
test('Docker digest duplicate differing only by case fails', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['docker-content-digest',`sha256:${H('a')}`],['docker-content-digest',`sha256:${H('A')}`]),load()),code('REGISTRY_HEADER_CONFLICT')));
test('Docker digest duplicate differing only by whitespace fails', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['docker-content-digest',`sha256:${H('1')}`],['docker-content-digest',`sha256:${H('1')} `]),load()),code('REGISTRY_HEADER_CONFLICT')));
test('conflicting duplicate auth realm fails', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['www-authenticate',challenge()],['www-authenticate',challenge({realm:'https://auth.docker.io/other'})]),load()),code('REGISTRY_AUTH_CONFLICT')));
test('conflicting duplicate auth service fails', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['www-authenticate',challenge()],['www-authenticate',challenge({service:'other'})]),load()),code('REGISTRY_AUTH_CONFLICT')));
test('conflicting duplicate auth scope fails', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['www-authenticate',challenge()],['www-authenticate',challenge({scope:'repository:supabase/other:pull'})]),load()),code('REGISTRY_AUTH_CONFLICT')));
test('semantically equivalent duplicate Bearer challenges collapse', () => { const first=challenge(), second=challenge({separator:',\t'}); assert.equal(canonicalizeProtectedHeaders(raw(['WWW-Authenticate',first],['www-authenticate',second]),load())['www-authenticate'],first); });
test('quoted commas are parsed within auth parameter values rather than split', () => { const value=challenge({realm:'https://auth.docker.io/to,ken'}); assert.equal(canonicalizeProtectedHeaders(raw(['www-authenticate',value]),load())['www-authenticate'],value); assert.throws(()=>parseAnonymousBearerChallenge(value,source()),code('REGISTRY_AUTH_REALM')); });
test('multiple auth schemes are rejected', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['www-authenticate',challenge()+', Basic realm="other"']),load()),code('REGISTRY_AUTH_CHALLENGE')));
test('malformed auth challenge is rejected', () => assert.throws(()=>canonicalizeProtectedHeaders(raw(['www-authenticate','Bearer realm="unterminated']),load()),code('REGISTRY_AUTH_CHALLENGE')));
test('protected header casing is normalized only at the field-name layer', () => { const value=`sha256:${H('1')}`; assert.equal(canonicalizeProtectedHeaders(raw(['DoCkEr-CoNtEnT-DiGeSt',value],['docker-content-digest',value]),load())['docker-content-digest'],value); });
test('already comma-coalesced Docker digest value is not split or accepted', async () => { const queue=anonymousQueue(); queue[2].headers['docker-content-digest']=`${queue[2].headers['docker-content-digest']}, ${queue[2].headers['docker-content-digest']}`; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_DIGEST_HEADER')); });
test('raw separate protected lines are the sole multiplicity authority', () => { const value=`sha256:${H('1')}`; assert.deepEqual(canonicalizeProtectedHeaders(raw(['content-type','application/json'],['docker-content-digest',value]),load()),{'content-type':'application/json','docker-content-digest':value}); assert.throws(()=>canonicalizeProtectedHeaders({'docker-content-digest':[value]},load()),code('REGISTRY_RAW_HEADERS')); });
test('one runtime Set-Cookie array occurrence is represented without duplicate processing or value retention', () => { const projected=canonicalizeProtectedHeaders(raw(['set-cookie','secret-cookie=value; Secure']),load()); assert.deepEqual(projected,{'set-cookie':'PRESENT_REJECTED'}); assert.doesNotMatch(JSON.stringify(projected),/secret-cookie|value/); });
test('multiple Set-Cookie lines remain non-persisted and response-rejected', async () => { const queue=anonymousQueue(); queue[1].headers['set-cookie']='PRESENT_REJECTED'; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_COOKIE')); });
test('unknown protected-header policy cannot be introduced', () => { const value=load(); value.protected_header_policy.headers['x-unknown-protected']='BYTE_IDENTICAL_DUPLICATE_COLLAPSIBLE'; assert.throws(()=>validateRegistryResolverContract(value),code('REGISTRY_HEADER_RULES')); });
test('token response without Set-Cookie has an exact absent projection', () => { const projected=projectProtectedResponseHeaders(raw(['Content-Type','application/json']),load()); assert.deepEqual(projected.response_cookie,{present:false,raw_occurrence_count:0}); assert.equal(validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)).disposition,'ABSENT'); });
test('one token-endpoint Set-Cookie is received as non-participating', () => { const projected=projectProtectedResponseHeaders(raw(['Set-Cookie','__cf_bm=opaque; Secure']),load()); assert.deepEqual(projected.response_cookie,{present:true,raw_occurrence_count:1}); assert.equal(validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)).disposition,'RECEIVED_NON_PARTICIPATING'); });
test('multiple token-endpoint Set-Cookie fields remain count-only', () => { const projected=projectProtectedResponseHeaders(raw(['set-cookie','a=one'],['set-cookie','b=two']),load()); assert.deepEqual(projected.response_cookie,{present:true,raw_occurrence_count:2}); assert.equal(validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)).raw_occurrence_count,2); assert.doesNotMatch(JSON.stringify(projected),/one|two/); });
test('Set-Cookie from registry manifest endpoint is rejected', () => { const projected=projectProtectedResponseHeaders(raw(['set-cookie','a=one']),load()); assert.throws(()=>validateResponseCookieNonParticipation(cookieContext(projected.response_cookie,{host:'registry-1.docker.io',path:'/v2/supabase/gotrue/manifests/v2.195.0',purpose:'TOP_LEVEL_MANIFEST'})),code('REGISTRY_COOKIE_CONTEXT')); });
test('Set-Cookie from unexpected host is rejected', () => { const projected=projectProtectedResponseHeaders(raw(['set-cookie','a=one']),load()); assert.throws(()=>validateResponseCookieNonParticipation(cookieContext(projected.response_cookie,{host:'unexpected.example'})),code('REGISTRY_COOKIE_CONTEXT')); });
test('outbound Cookie header attempt is rejected', () => assert.throws(()=>validateResponseCookieNonParticipation(cookieContext({present:false,raw_occurrence_count:0},{requestHeaders:{accept:'application/json',cookie:'a=one'}})),code('REGISTRY_COOKIE_OUTBOUND')));
test('cookie jar configuration attempt is rejected', () => assert.throws(()=>validateResponseCookieNonParticipation(cookieContext({present:false,raw_occurrence_count:0},{cookieJar:'ENABLED'})),code('REGISTRY_COOKIE_JAR')));
test('cookie replay attempt remains an outbound Cookie rejection', () => assert.throws(()=>validateResponseCookieNonParticipation(cookieContext({present:true,raw_occurrence_count:1},{requestHeaders:{accept:'application/json',cookie:'replayed=one'}})),code('REGISTRY_COOKIE_OUTBOUND')));
test('redirect carrying a cookie is rejected', () => assert.throws(()=>validateResponseCookieNonParticipation(cookieContext({present:true,raw_occurrence_count:1},{responseStatusCode:302})),code('REGISTRY_COOKIE_REDIRECT')));
test('cookie value is not exposed to higher-level resolver result', async () => { const projected=projectProtectedResponseHeaders(raw(['content-type','application/json'],['set-cookie','secret-cookie=opaque']),load()); validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)); const queue=anonymousQueue(); queue[1].headers=projected.headers; const {result}=await resolveWith(queue); assert.doesNotMatch(JSON.stringify(result),/secret-cookie|opaque|cookie/i); });
test('resolver cookie path has no persistence primitive', () => { const text=fs.readFileSync(new URL('../lib/registry-digest-resolver.mjs',import.meta.url),'utf8'); assert.doesNotMatch(text,/writeFile|appendFile|createWriteStream|from ['"](?:tough-cookie|fetch-cookie)|new CookieJar|\.setCookie\(/i); });
test('resolver cookie path has no logging primitive', () => { const text=fs.readFileSync(new URL('../lib/registry-digest-resolver.mjs',import.meta.url),'utf8'); assert.doesNotMatch(text,/console\.|process\.stdout|process\.stderr|logger\./i); });
test('token validation succeeds independently after approved cookie discard', async () => { const projected=projectProtectedResponseHeaders(raw(['content-type','application/json'],['set-cookie','a=one']),load()); validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)); const queue=anonymousQueue(); queue[1].headers=projected.headers; assert.equal((await resolveWith(queue)).result.network.anonymous_auth,'ANONYMOUS_BEARER'); });
test('token failure remains failure despite approved cookie receipt', async () => { const projected=projectProtectedResponseHeaders(raw(['content-type','application/json'],['set-cookie','a=one']),load()); validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)); const queue=anonymousQueue(); queue[1]={status:200,headers:projected.headers,body:json({message:'no token'})}; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_TOKEN_FIELDS')); });
test('digest approval path cannot read cookie projection', async () => { const projected=projectProtectedResponseHeaders(raw(['content-type','application/json'],['set-cookie','a=one']),load()); validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)); const queue=anonymousQueue(); queue[1].headers=projected.headers; const {result}=await resolveWith(queue); assert.deepEqual(Object.keys(result.network).sort(),['anonymous_auth','filesystem_layers_downloaded','metadata_only']); });
test('Set-Cookie field name matching is case-insensitive', () => assert.deepEqual(projectProtectedResponseHeaders(raw(['sEt-CoOkIe','a=one']),load()).response_cookie,{present:true,raw_occurrence_count:1}));
test('malformed cookie field fails low-level structural validation', () => assert.throws(()=>projectProtectedResponseHeaders(raw(['set-cookie','not-a-cookie']),load()),code('REGISTRY_COOKIE_MALFORMED')));
test('zero-length cookie value remains valid non-participating metadata', () => { const projected=projectProtectedResponseHeaders(raw(['set-cookie','empty=']),load()); assert.equal(validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)).disposition,'RECEIVED_NON_PARTICIPATING'); });
test('unexpected token endpoint path is rejected', () => assert.throws(()=>validateResponseCookieNonParticipation(cookieContext({present:true,raw_occurrence_count:1},{path:'/other?service=registry.docker.io&scope=repository%3Asupabase%2Fgotrue%3Apull'})),code('REGISTRY_COOKIE_ENDPOINT')));
test('cookie projection contains presence and count only', () => { const projected=projectProtectedResponseHeaders(raw(['set-cookie','__cf_bm=opaque; Expires=never']),load()).response_cookie; assert.deepEqual(Object.keys(projected).sort(),['present','raw_occurrence_count']); assert.deepEqual(projected,{present:true,raw_occurrence_count:1}); });
test('valid token-only response selects one opaque credential', () => assert.equal(parseRegistryTokenResponse(json({token:'opaque.token'}),load()),'opaque.token'));
test('valid access_token-only response selects one opaque credential', () => assert.equal(parseRegistryTokenResponse(json({access_token:'opaque.access'}),load()),'opaque.access'));
test('byte-identical token aliases are accepted deterministically', () => assert.equal(parseRegistryTokenResponse(json({token:'same.value',access_token:'same.value'}),load()),'same.value'));
test('conflicting token aliases fail closed', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'first',access_token:'second'}),load()),code('REGISTRY_TOKEN_CONFLICT')));
test('token wrong type is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:7}),load()),code('REGISTRY_TOKEN_VALUE')));
test('token null is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:null}),load()),code('REGISTRY_TOKEN_VALUE')));
test('token empty is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:''}),load()),code('REGISTRY_TOKEN_VALUE')));
test('token whitespace-only is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'   '}),load()),code('REGISTRY_TOKEN_VALUE')));
test('token exceeding the explicit 16384-character bound is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'a'.repeat(16385)}),load()),code('REGISTRY_TOKEN_VALUE')));
test('token control characters are rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'safe\u0001unsafe'}),load()),code('REGISTRY_TOKEN_VALUE')));
test('missing token field is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({expires_in:300}),load()),code('REGISTRY_TOKEN_VALUE')));
test('duplicate token JSON key is rejected before object construction', () => assert.throws(()=>parseRegistryTokenResponse(Buffer.from('{"token":"first","token":"second"}'),load()),code('REGISTRY_TOKEN_JSON')));
test('duplicate access_token JSON key is rejected before object construction', () => assert.throws(()=>parseRegistryTokenResponse(Buffer.from('{"access_token":"first","access_token":"second"}'),load()),code('REGISTRY_TOKEN_JSON')));
test('duplicate alias key remains rejected even beside the equivalent alias', () => assert.throws(()=>parseRegistryTokenResponse(Buffer.from('{"token":"same","access_token":"same","token":"same"}'),load()),code('REGISTRY_TOKEN_JSON')));
test('expires_in accepts a safe integer of at least sixty seconds', () => assert.equal(parseRegistryTokenResponse(json({token:'opaque',expires_in:300}),load()),'opaque'));
test('expires_in invalid type is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'opaque',expires_in:'300'}),load()),code('REGISTRY_TOKEN_EXPIRES')));
test('issued_at accepts an exact RFC3339 UTC instant', () => assert.equal(parseRegistryTokenResponse(json({token:'opaque',issued_at:'2026-08-30T06:03:20.749Z'}),load()),'opaque'));
test('issued_at malformed or impossible date is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'opaque',issued_at:'2026-02-30T00:00:00Z'}),load()),code('REGISTRY_TOKEN_ISSUED_AT')));
test('unknown benign metadata field is rejected by the exact field set', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'opaque',note:'benign'}),load()),code('REGISTRY_TOKEN_FIELDS')));
test('unknown token-like credential field is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:'opaque',refresh_token:'other.credential'}),load()),code('REGISTRY_TOKEN_FIELDS')));
test('nested token object is rejected', () => assert.throws(()=>parseRegistryTokenResponse(json({token:{value:'opaque'}}),load()),code('REGISTRY_TOKEN_VALUE')));
test('token parser has no logging primitive', () => { const text=fs.readFileSync(new URL('../lib/registry-digest-resolver.mjs',import.meta.url),'utf8'); assert.doesNotMatch(text,/console\.|process\.stdout|process\.stderr|logger\./i); });
test('token parser has no persistence primitive', () => { const text=fs.readFileSync(new URL('../lib/registry-digest-resolver.mjs',import.meta.url),'utf8'); assert.doesNotMatch(text,/writeFile|appendFile|createWriteStream|localStorage|sessionStorage/i); });
test('token remains memory-only and absent from resolver output', async () => { const {result}=await resolveWith(anonymousQueue()); assert.doesNotMatch(JSON.stringify(result),/safe\.synthetic\.token/); });
test('cookie presence cannot alter token alias selection', () => { const projected=projectProtectedResponseHeaders(raw(['set-cookie','a=one']),load()); validateResponseCookieNonParticipation(cookieContext(projected.response_cookie)); assert.equal(parseRegistryTokenResponse(json({token:'same',access_token:'same'}),load()),'same'); });
test('repository scope remains challenge and request bound rather than token-payload bound', () => { assert.equal(parseRegistryTokenResponse(json({token:'opaque'}),load()),'opaque'); assert.throws(()=>parseAnonymousBearerChallenge(challenge({scope:'repository:supabase/other:pull'}),source()),code('REGISTRY_AUTH_SCOPE')); });
test('parser return is exactly one opaque string credential', () => { const selected=parseRegistryTokenResponse(json({token:'opaque',access_token:'opaque',expires_in:300,issued_at:'2026-08-30T06:03:20Z'}),load()); assert.equal(typeof selected,'string'); assert.equal(selected,'opaque'); });
test('anonymous token remains absent from result and evidence', async () => { const {result,calls}=await resolveWith(anonymousQueue()); assert.doesNotMatch(JSON.stringify(result),/safe\.synthetic\.token|authorization/i); assert.ok(calls.some(call=>typeof call.headers.authorization==='string')); });
test('timeout is surfaced without retry', async () => { let calls=0; await assert.rejects(()=>resolveRegistryDigest({contract:load(),role:'AUTH',sourceReference:'supabase/gotrue:v2.195.0',resolverSha256:H('a'),request:async()=>{calls+=1;throw Object.assign(new Error('timeout'),{code:'REGISTRY_TIMEOUT'});}})); assert.equal(calls,1); });
test('rate limit fails without retry', async () => { let calls=0; await assert.rejects(()=>resolveRegistryDigest({contract:load(),role:'AUTH',sourceReference:'supabase/gotrue:v2.195.0',resolverSha256:H('a'),request:async()=>{calls+=1;return{status:429,headers:{},body:Buffer.from('rate')};}}),code('REGISTRY_RATE_LIMIT')); assert.equal(calls,1); });
test('config body bound is enforced', async () => { const queue=anonymousQueue(); queue[4]={status:200,headers:{},body:Buffer.alloc(load().bounds.config_body_bytes+1)}; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_CONFIG_BODY')); });
test('config descriptor digest relationship is exact', async () => { const queue=anonymousQueue(); queue[4].body=Buffer.alloc(queue[4].body.length,0); await assert.rejects(()=>resolveWith(queue),code('REGISTRY_CONFIG_DIGEST_MISMATCH')); });
test('tag-only or digest substitution is rejected', () => assert.throws(()=>parseApprovedSourceReference(load(),'AUTH',`supabase/gotrue@sha256:${H('1')}`),code('REGISTRY_UNAPPROVED_SOURCE')));
test('registry host drift is rejected by contract', () => { const value=load(); value.approved_sources[0].registry_host='registry.example'; assert.throws(()=>validateRegistryResolverContract(value),code('REGISTRY_SOURCE_VALUE')); });
test('repository mismatch is rejected', () => assert.throws(()=>parseApprovedSourceReference(load(),'AUTH','other/gotrue:v2.195.0'),code('REGISTRY_UNAPPROVED_SOURCE')));
test('source-reference normalization attack is rejected', () => assert.throws(()=>parseApprovedSourceReference(load(),'AUTH','SUPABASE/gotrue:v2.195.0'),code('REGISTRY_UNAPPROVED_SOURCE')));
test('uppercase or malformed digest is rejected', () => { const a=artifacts(); a.index.manifests[0].digest=`sha256:${H('A')}`; assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_DESCRIPTOR')); });
test('duplicate role approval source is rejected', () => { const value=load(); value.approved_sources.push(clone(value.approved_sources[0])); assert.throws(()=>validateRegistryResolverContract(value),code('REGISTRY_SOURCE_DUPLICATE')); });
test('safe config projection excludes environment values and records volumes structurally', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',config:{Env:['SECRET=value'],Volumes:{'/safe':{}},Entrypoint:['run']}}}); const {result}=await resolveWith(anonymousQueue(a)); assert.deepEqual(result.declared_volumes,['/safe']); assert.doesNotMatch(JSON.stringify(result),/SECRET=value/); });
test('resolver module has no Docker, credential-file, environment, layer-download, shell, or writer path', () => { const text=fs.readFileSync(new URL('../lib/registry-digest-resolver.mjs',import.meta.url),'utf8'); assert.doesNotMatch(text,/node:child_process|execFile|spawn\(|process\.env|\.docker\/config|credentialHelper|docker\s+pull|writeFile|appendFile|createWriteStream|\/layers\//i); });
test('config redirect contract is exact and config-only', () => { const policy=validateRegistryResolverContract(load()).config_blob_redirect_policy; assert.equal(policy.mode,'CONFIG_BLOB_ONE_HOP_CAPABILITY_REDIRECT'); assert.equal(policy.object_type,'EXACT_CHILD_CONFIG_DESCRIPTOR_ONLY'); assert.deepEqual(policy.accepted_statuses,[307]); });
test('immutable config blob direct 200 remains accepted without redirect callback', async () => { const a=artifacts(); let redirects=0; const {result,calls}=await fetchConfigWith(a,[a.configResponse],{onRedirect:()=>{redirects+=1;}}); assert.equal(result.computed_digest,a.configDigest); assert.equal(result.redirect,null); assert.equal(redirects,0); assert.equal(calls.length,1); });
test('approved config-only 307 redirect is followed once', async () => { const a=artifacts(), origin={status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)}; const {result,calls}=await fetchConfigWith(a,[origin,a.configResponse]); assert.equal(result.computed_digest,a.configDigest); assert.equal(result.redirect.redirect_hop_count,1); assert.equal(calls.length,2); });
test('approved redirect is HTTPS to HTTPS', () => assert.equal(redirectProjection().target_scheme,'https'));
test('HTTP config Location is rejected before redirected network activity', async () => { const a=artifacts(), calls=[]; await assert.rejects(()=>fetchImmutableConfigBlob({contract:load(),source:source(),configDescriptor:a.child.config,layerDigests:a.child.layers.map(x=>x.digest),requestedDigest:a.configDigest,authorization:null,request:async spec=>{calls.push(spec);return{status:307,headers:{location:'http://cdn.example.test/blob'},body:Buffer.alloc(0)};}}),code('REGISTRY_CONFIG_REDIRECT_TARGET')); assert.equal(calls.length,1); });
test('missing config redirect Location is rejected', () => assert.throws(()=>redirectProjection({response:{status:307,headers:{},body:Buffer.alloc(0)}}),code('REGISTRY_CONFIG_REDIRECT_LOCATION')));
test('malformed config redirect Location is rejected', () => assert.throws(()=>redirectProjection({response:{status:307,headers:{location:'not a URL'},body:Buffer.alloc(0)}}),code('REGISTRY_CONFIG_REDIRECT_LOCATION')));
test('302 config redirect status is rejected', async () => { const a=artifacts(); await assert.rejects(()=>fetchConfigWith(a,[{status:302,headers:{location:redirectLocation},body:Buffer.alloc(0)}]),code('REGISTRY_CONFIG_REDIRECT_STATUS')); });
test('308 config redirect status is rejected', async () => { const a=artifacts(); await assert.rejects(()=>fetchConfigWith(a,[{status:308,headers:{location:redirectLocation},body:Buffer.alloc(0)}]),code('REGISTRY_CONFIG_REDIRECT_STATUS')); });
test('second config redirect is rejected', async () => { const a=artifacts(); await assert.rejects(()=>fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},{status:307,headers:{location:'https://second.example.test/blob'},body:Buffer.alloc(0)}]),code('REGISTRY_CONFIG_REDIRECT_HOP')); });
test('config redirect loop is rejected as the forbidden second hop', async () => { const a=artifacts(); await assert.rejects(()=>fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)}]),code('REGISTRY_CONFIG_REDIRECT_HOP')); });
test('Authorization is absent from fresh cross-host redirect request', async () => { const a=artifacts(), {calls}=await fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},a.configResponse]); assert.equal(Object.hasOwn(calls[1].headers,'authorization'),false); });
test('Cookie is absent from fresh cross-host redirect request', async () => { const a=artifacts(), {calls}=await fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},a.configResponse]); assert.equal(Object.hasOwn(calls[1].headers,'cookie'),false); });
test('registry bearer token is not forwarded to redirect host', async () => { const a=artifacts(), {calls}=await fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},a.configResponse]); assert.doesNotMatch(JSON.stringify(calls[1]),/safe\.synthetic\.token|Bearer/); });
test('redirect query values are absent from safe projection', () => { const projection=redirectProjection(); assert.doesNotMatch(JSON.stringify(projection),/secret-value|60/); assert.deepEqual(projection.query_parameter_names,['X-Signature','X-Expires']); });
test('complete redirect URL is absent from retained projection', () => assert.equal(JSON.stringify(redirectProjection()).includes(redirectLocation),false));
test('redirect URL is passed byte-for-byte without reconstruction', async () => { const a=artifacts(), exactLocation='https://cdn.example.test/a%2Fb//c?X-Signature=a%2Bb%3D&X-Order=2'; const {calls}=await fetchConfigWith(a,[{status:307,headers:{location:exactLocation},body:Buffer.alloc(0)},a.configResponse]); assert.equal(calls[1].url,exactLocation); });
test('redirected config raw bytes matching descriptor digest pass', async () => { const a=artifacts(), {result}=await fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},a.configResponse]); assert.equal(result.computed_digest,a.child.config.digest); });
test('redirected config digest mismatch fails closed', async () => { const a=artifacts(), bad={status:200,headers:{},body:Buffer.alloc(a.configBytes.length,0)}; await assert.rejects(()=>fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},bad]),code('REGISTRY_CONFIG_DIGEST_MISMATCH')); });
test('redirected config declared descriptor size mismatch fails closed', async () => { const a=artifacts(), bad={status:200,headers:{},body:Buffer.concat([a.configBytes,Buffer.from(' ')])}; await assert.rejects(()=>fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},bad]),code('REGISTRY_CONFIG_SIZE_MISMATCH')); });
test('redirected oversized config body is rejected', async () => { const a=artifacts(), bad={status:200,headers:{},body:Buffer.alloc(load().bounds.config_body_bytes+1)}; await assert.rejects(()=>fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},bad]),code('REGISTRY_CONFIG_BODY')); });
test('redirected malformed config JSON is rejected after digest verification', async () => { const a=replaceConfigBytes(artifacts(),Buffer.from('{')); await assert.rejects(()=>resolveWith(redirectedQueue(a)),code('REGISTRY_CONFIG_JSON')); });
test('redirected config duplicate JSON keys are rejected strictly', async () => { const bytes=Buffer.from('{"architecture":"arm64","architecture":"arm64","os":"linux","config":{}}'); const a=replaceConfigBytes(artifacts(),bytes); await assert.rejects(()=>resolveWith(redirectedQueue(a)),code('REGISTRY_CONFIG_JSON')); });
test('redirected config OS mismatch is rejected', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'windows',config:{}}}); await assert.rejects(()=>resolveWith(redirectedQueue(a)),code('REGISTRY_CONFIG_PLATFORM')); });
test('redirected config architecture mismatch is rejected', async () => { const a=artifacts({configValue:{architecture:'amd64',os:'linux',config:{}}}); await assert.rejects(()=>resolveWith(redirectedQueue(a)),code('REGISTRY_CONFIG_PLATFORM')); });
test('redirected config explicit variant mismatch is rejected', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',variant:'v9',config:{}}}); await assert.rejects(()=>resolveWith(redirectedQueue(a)),code('REGISTRY_CONFIG_VARIANT')); });
test('redirected config omitted variant passes frozen arm64 v8 rule', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',config:{}}}); assert.deepEqual((await resolveWith(redirectedQueue(a))).result.platform,platform); });
test('redirected config null variant passes OCI config absent-equivalence rule', async () => { const a=artifacts({configValue:{architecture:'arm64',os:'linux',variant:null,config:{}}}); assert.deepEqual((await resolveWith(redirectedQueue(a))).result.platform,platform); });
test('layer digest cannot enter config redirect flow and causes no network', async () => { const a=artifacts(), calls=[]; await assert.rejects(()=>fetchImmutableConfigBlob({contract:load(),source:source(),configDescriptor:a.child.config,layerDigests:a.child.layers.map(x=>x.digest),requestedDigest:a.child.layers[0].digest,authorization:null,request:async spec=>{calls.push(spec);}}),code('REGISTRY_CONFIG_BLOB_NOT_CONFIG')); assert.equal(calls.length,0); });
test('manifest redirect remains rejected under global no-redirect policy', async () => { const queue=anonymousQueue(); queue[2]={status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)}; await assert.rejects(()=>resolveWith(queue),code('REGISTRY_UNEXPECTED_REDIRECT')); });
test('unexpected config redirect source endpoint is rejected', () => assert.throws(()=>redirectProjection({sourcePath:'/v2/supabase/gotrue/blobs/not-the-config-digest'}),code('REGISTRY_CONFIG_REDIRECT_SOURCE_ENDPOINT')));
test('redirect transport request method remains an explicit GET', () => { const text=fs.readFileSync(new URL('../lib/registry-digest-resolver.mjs',import.meta.url),'utf8'); assert.match(text,/const requestOptions = \{ method: 'GET'/); });
test('approved redirect makes exactly one target request and no retry', async () => { const a=artifacts(), {calls}=await fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},a.configResponse]); assert.deepEqual(calls.map(x=>x.purpose),['CONFIG_METADATA_BLOB','CONFIG_METADATA_BLOB_REDIRECT']); });
test('safe redirect reporting contains only query names and structural path data', () => { const projection=redirectProjection(); assert.deepEqual(projection.location_path_structure,{absolute:true,segment_count:3,trailing_slash:false}); assert.deepEqual(Object.keys(projection).sort(),['authorization_sent','cookie_sent','explicit_port','location_byte_length','location_path_structure','location_sha256','query_parameter_count','query_parameter_names','redirect_hop_count','redirect_request_header_names','requested_config_digest','source_host','source_repository','status','target_host','target_scheme'].sort()); });
test('raw descriptor projection distinguishes omitted variant', () => { const a=artifacts(); delete a.index.manifests[0].platform.variant; const row=projectIndexPlatformDescriptors(a.index,load())[0]; assert.equal(row.variant_present,false); assert.equal(row.variant_json_type,'ABSENT'); });
test('raw descriptor projection distinguishes explicit null variant', () => { const a=artifacts(); a.index.manifests[0].platform.variant=null; const row=projectIndexPlatformDescriptors(a.index,load())[0]; assert.equal(row.variant_present,true); assert.equal(row.variant_json_type,'null'); });
test('raw descriptor projection distinguishes explicit v8 variant', () => { const row=projectIndexPlatformDescriptors(artifacts().index,load())[0]; assert.equal(row.variant_present,true); assert.equal(row.variant_json_type,'string'); assert.equal(row.variant_value,'v8'); });
test('presence-aware multiple compatible executable descriptors still fail ambiguous', () => { const a=artifacts(); const omitted=clone(a.index.manifests[0]); delete omitted.platform.variant; omitted.digest=`sha256:${H('b')}`; a.index.manifests.push(omitted); assert.throws(()=>select(a.index),code('REGISTRY_PLATFORM_AMBIGUOUS')); });
test('redirect Location length and hash cover the complete secret-capable value', () => { const projection=redirectProjection(); assert.equal(projection.location_byte_length,Buffer.byteLength(redirectLocation)); assert.equal(projection.location_sha256,digest(Buffer.from(redirectLocation))); });
test('redirect request header allowlist is exactly accept', async () => { const a=artifacts(), {calls}=await fetchConfigWith(a,[{status:307,headers:{location:redirectLocation},body:Buffer.alloc(0)},a.configResponse]); assert.deepEqual(Object.keys(calls[1].headers),['accept']); });
test('credential-bearing redirect URL is rejected', () => assert.throws(()=>redirectProjection({response:{status:307,headers:{location:'https://user:pass@cdn.example.test/blob'},body:Buffer.alloc(0)}}),code('REGISTRY_CONFIG_REDIRECT_TARGET')));
test('redirect URL fragment is rejected', () => assert.throws(()=>redirectProjection({response:{status:307,headers:{location:'https://cdn.example.test/blob#fragment'},body:Buffer.alloc(0)}}),code('REGISTRY_CONFIG_REDIRECT_TARGET')));
test('non-default explicit redirect port is rejected', () => assert.throws(()=>redirectProjection({response:{status:307,headers:{location:'https://cdn.example.test:8443/blob'},body:Buffer.alloc(0)}}),code('REGISTRY_CONFIG_REDIRECT_PORT')));
test('explicit HTTPS default port is retained in safe projection', () => assert.equal(redirectProjection({response:{status:307,headers:{location:'https://cdn.example.test:443/blob'},body:Buffer.alloc(0)}}).explicit_port,'443'));
test('IP-literal redirect host is rejected', () => assert.throws(()=>redirectProjection({response:{status:307,headers:{location:'https://127.0.0.1/blob'},body:Buffer.alloc(0)}}),code('REGISTRY_CONFIG_REDIRECT_HOST')));
test('over-bound Location is rejected before target request', () => assert.throws(()=>redirectProjection({response:{status:307,headers:{location:`https://cdn.example.test/blob?x=${'a'.repeat(8192)}`},body:Buffer.alloc(0)}}),code('REGISTRY_CONFIG_REDIRECT_LOCATION')));
